pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y build-essential'
                sh 'make'
            }
        }

        stage('Package') {
            steps {
                sh 'make package'
            }
        }

        stage('Publish') {
            steps {
                // Add your publish steps here
            }
        }
    }
}